/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.anamnese.view;

import br.com.anamnese.dao.AnamneseDAO;
import br.com.anamnese.model.Anamnese;
import br.com.anamnese.model.Pacientes;

/**
 *
 * @author Marcelo Saorim
 */
public class FrmAnamnese extends javax.swing.JFrame {

    /**
     * Creates new form FrmAnamnese
     */
    public FrmAnamnese() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Circulatorios = new javax.swing.ButtonGroup();
        Renais = new javax.swing.ButtonGroup();
        Respiratorios = new javax.swing.ButtonGroup();
        Digestivos = new javax.swing.ButtonGroup();
        Endocrinos = new javax.swing.ButtonGroup();
        Gastro = new javax.swing.ButtonGroup();
        Ginecologicos = new javax.swing.ButtonGroup();
        Pressao = new javax.swing.ButtonGroup();
        Cardiacos = new javax.swing.ButtonGroup();
        Hepaticos = new javax.swing.ButtonGroup();
        Diabetes = new javax.swing.ButtonGroup();
        Anemias = new javax.swing.ButtonGroup();
        Epilepsia = new javax.swing.ButtonGroup();
        Colesterol = new javax.swing.ButtonGroup();
        Hipo = new javax.swing.ButtonGroup();
        Hiper = new javax.swing.ButtonGroup();
        Cancer = new javax.swing.ButtonGroup();
        Depressao = new javax.swing.ButtonGroup();
        Herpes = new javax.swing.ButtonGroup();
        Audicao = new javax.swing.ButtonGroup();
        Alergias = new javax.swing.ButtonGroup();
        Cirurgia = new javax.swing.ButtonGroup();
        Plastica = new javax.swing.ButtonGroup();
        Gravida = new javax.swing.ButtonGroup();
        Lentes = new javax.swing.ButtonGroup();
        Obturacoes = new javax.swing.ButtonGroup();
        Aparelho = new javax.swing.ButtonGroup();
        Placas = new javax.swing.ButtonGroup();
        MarcaPasso = new javax.swing.ButtonGroup();
        DIU = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroAnamnese = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQueixa = new javax.swing.JTextField();
        PaneAnamnese = new javax.swing.JTabbedPane();
        panelHabitosDeVida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsVida = new javax.swing.JTextArea();
        panelProblemasDeSaude = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jRadioButton18 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        rbAlergiasNao = new javax.swing.JRadioButton();
        rbAlergiasSim = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlergias = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObsSaude = new javax.swing.JTextArea();
        panelProcedimentosCirurgicos = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        rbCirurgiaNao = new javax.swing.JRadioButton();
        rbCirurgiaSim = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        txtCirurgia = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        rbPlasticaNao = new javax.swing.JRadioButton();
        rbPlasticaSim = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        txtPlastica = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtObsCirurgia = new javax.swing.JTextArea();
        panelOutros = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jRadioButton47 = new javax.swing.JRadioButton();
        jRadioButton48 = new javax.swing.JRadioButton();
        jRadioButton49 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jLabel43 = new javax.swing.JLabel();
        jRadioButton51 = new javax.swing.JRadioButton();
        jRadioButton52 = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jLabel45 = new javax.swing.JLabel();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jLabel47 = new javax.swing.JLabel();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        panelFotos = new javax.swing.JPanel();
        btnCapturarImagem2 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        btnCapturarImagem3 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        btnCapturarImagem4 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        btnCapturarImagem1 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        btnCarregarImagem1 = new javax.swing.JButton();
        btnCarregarImagem2 = new javax.swing.JButton();
        btnCarregarImagem3 = new javax.swing.JButton();
        btnCarregarImagem4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnImprimeFicha = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha de Anamnese");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 50, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ficha de Anamnese");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 51);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 72, 41, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Anamnese Nº");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(620, 70, 90, 20);

        txtNumeroAnamnese.setEditable(false);
        txtNumeroAnamnese.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtNumeroAnamnese);
        txtNumeroAnamnese.setBounds(714, 70, 120, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Principal Queixa:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 106, 100, 17);

        txtQueixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtQueixa);
        txtQueixa.setBounds(114, 103, 720, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Ingestão de bebidas alcoólicas:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Ocasionalmente", "Frequentemente" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Qualidade do sono:");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tranquilo", "Agitado" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Fumante:");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Ingestão de água/dia:");

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 litros", "1 litro", "Menos de 1 litro" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Alimentação:");

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pouco calórica", "Balanceada", "Muito calórica" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Evacua regularmente::");

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Uso contínuo de medicação:");

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Qual?");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Atividade física:");

        jComboBox8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Qual?");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Observações:");

        txtObsVida.setColumns(20);
        txtObsVida.setLineWrap(true);
        txtObsVida.setRows(5);
        txtObsVida.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtObsVida);

        javax.swing.GroupLayout panelHabitosDeVidaLayout = new javax.swing.GroupLayout(panelHabitosDeVida);
        panelHabitosDeVida.setLayout(panelHabitosDeVidaLayout);
        panelHabitosDeVidaLayout.setHorizontalGroup(
            panelHabitosDeVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabitosDeVidaLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panelHabitosDeVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelHabitosDeVidaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHabitosDeVidaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHabitosDeVidaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(panelHabitosDeVidaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5))
                    .addGroup(panelHabitosDeVidaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        panelHabitosDeVidaLayout.setVerticalGroup(
            panelHabitosDeVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHabitosDeVidaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(panelHabitosDeVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitosDeVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitosDeVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitosDeVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHabitosDeVidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PaneAnamnese.addTab("Hábitos de Vida", panelHabitosDeVida);

        panelProblemasDeSaude.setLayout(null);

        jLabel16.setText("Problemas Ginecológicos:");
        panelProblemasDeSaude.add(jLabel16);
        jLabel16.setBounds(10, 164, 120, 14);

        jLabel17.setText("Problemas Circulatórios:");
        panelProblemasDeSaude.add(jLabel17);
        jLabel17.setBounds(10, 11, 115, 14);

        jLabel18.setText("Problemas Renais:");
        panelProblemasDeSaude.add(jLabel18);
        jLabel18.setBounds(10, 37, 88, 14);

        Renais.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Não");
        panelProblemasDeSaude.add(jRadioButton1);
        jRadioButton1.setBounds(152, 33, 45, 23);

        Renais.add(jRadioButton2);
        jRadioButton2.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton2);
        jRadioButton2.setBounds(199, 33, 41, 23);

        Circulatorios.add(jRadioButton3);
        jRadioButton3.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton3);
        jRadioButton3.setBounds(199, 7, 41, 23);

        Circulatorios.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("Não");
        panelProblemasDeSaude.add(jRadioButton4);
        jRadioButton4.setBounds(152, 7, 45, 23);

        Ginecologicos.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Não");
        panelProblemasDeSaude.add(jRadioButton5);
        jRadioButton5.setBounds(152, 160, 45, 23);

        Ginecologicos.add(jRadioButton6);
        jRadioButton6.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton6);
        jRadioButton6.setBounds(199, 160, 41, 23);

        jLabel19.setText("Problemas Respiratórios:");
        panelProblemasDeSaude.add(jLabel19);
        jLabel19.setBounds(10, 63, 119, 14);

        Respiratorios.add(jRadioButton7);
        jRadioButton7.setSelected(true);
        jRadioButton7.setText("Não");
        panelProblemasDeSaude.add(jRadioButton7);
        jRadioButton7.setBounds(152, 59, 45, 23);

        Respiratorios.add(jRadioButton8);
        jRadioButton8.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton8);
        jRadioButton8.setBounds(199, 59, 41, 23);

        Digestivos.add(jRadioButton9);
        jRadioButton9.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton9);
        jRadioButton9.setBounds(199, 85, 41, 23);

        jLabel20.setText("Problemas Digestivos:");
        panelProblemasDeSaude.add(jLabel20);
        jLabel20.setBounds(10, 89, 105, 14);

        Digestivos.add(jRadioButton10);
        jRadioButton10.setSelected(true);
        jRadioButton10.setText("Não");
        panelProblemasDeSaude.add(jRadioButton10);
        jRadioButton10.setBounds(152, 85, 45, 23);

        jLabel21.setText("Problemas Endócrinos");
        panelProblemasDeSaude.add(jLabel21);
        jLabel21.setBounds(10, 115, 104, 14);

        Endocrinos.add(jRadioButton11);
        jRadioButton11.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton11);
        jRadioButton11.setBounds(199, 111, 41, 23);

        Endocrinos.add(jRadioButton12);
        jRadioButton12.setSelected(true);
        jRadioButton12.setText("Não");
        panelProblemasDeSaude.add(jRadioButton12);
        jRadioButton12.setBounds(152, 111, 45, 23);

        Gastro.add(jRadioButton13);
        jRadioButton13.setSelected(true);
        jRadioButton13.setText("Não");
        panelProblemasDeSaude.add(jRadioButton13);
        jRadioButton13.setBounds(152, 137, 45, 23);

        Gastro.add(jRadioButton14);
        jRadioButton14.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton14);
        jRadioButton14.setBounds(199, 137, 41, 23);

        jLabel22.setText("Problemas Gastrointestinais:");
        panelProblemasDeSaude.add(jLabel22);
        jLabel22.setBounds(10, 141, 136, 14);

        jLabel23.setText("Problemas Pressão Arterial:");
        panelProblemasDeSaude.add(jLabel23);
        jLabel23.setBounds(10, 187, 132, 14);

        Pressao.add(jRadioButton15);
        jRadioButton15.setSelected(true);
        jRadioButton15.setText("Não");
        panelProblemasDeSaude.add(jRadioButton15);
        jRadioButton15.setBounds(152, 183, 45, 23);

        Pressao.add(jRadioButton16);
        jRadioButton16.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton16);
        jRadioButton16.setBounds(199, 183, 41, 23);

        Cardiacos.add(jRadioButton17);
        jRadioButton17.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton17);
        jRadioButton17.setBounds(199, 206, 41, 23);

        jLabel24.setText("Problemas Cardíacos:");
        panelProblemasDeSaude.add(jLabel24);
        jLabel24.setBounds(10, 210, 103, 14);

        Cardiacos.add(jRadioButton18);
        jRadioButton18.setSelected(true);
        jRadioButton18.setText("Não");
        panelProblemasDeSaude.add(jRadioButton18);
        jRadioButton18.setBounds(152, 206, 45, 23);

        jLabel25.setText("Problemas Hepáticos:");
        panelProblemasDeSaude.add(jLabel25);
        jLabel25.setBounds(10, 233, 103, 14);

        Hepaticos.add(jRadioButton19);
        jRadioButton19.setSelected(true);
        jRadioButton19.setText("Não");
        panelProblemasDeSaude.add(jRadioButton19);
        jRadioButton19.setBounds(152, 229, 45, 23);

        Hepaticos.add(jRadioButton20);
        jRadioButton20.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton20);
        jRadioButton20.setBounds(199, 229, 41, 23);

        jLabel26.setText("Colesterol:");
        panelProblemasDeSaude.add(jLabel26);
        jLabel26.setBounds(343, 88, 52, 14);

        Colesterol.add(jRadioButton21);
        jRadioButton21.setSelected(true);
        jRadioButton21.setText("Não");
        panelProblemasDeSaude.add(jRadioButton21);
        jRadioButton21.setBounds(450, 84, 45, 23);

        jLabel27.setText("Hipotireoidismo:");
        panelProblemasDeSaude.add(jLabel27);
        jLabel27.setBounds(343, 114, 76, 14);

        Hipo.add(jRadioButton22);
        jRadioButton22.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton22);
        jRadioButton22.setBounds(497, 110, 41, 23);

        Hipo.add(jRadioButton23);
        jRadioButton23.setSelected(true);
        jRadioButton23.setText("Não");
        panelProblemasDeSaude.add(jRadioButton23);
        jRadioButton23.setBounds(450, 110, 45, 23);

        Hiper.add(jRadioButton24);
        jRadioButton24.setSelected(true);
        jRadioButton24.setText("Não");
        panelProblemasDeSaude.add(jRadioButton24);
        jRadioButton24.setBounds(450, 136, 45, 23);

        Hiper.add(jRadioButton25);
        jRadioButton25.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton25);
        jRadioButton25.setBounds(497, 136, 41, 23);

        jLabel28.setText("Câncer:");
        panelProblemasDeSaude.add(jLabel28);
        jLabel28.setBounds(343, 163, 38, 14);

        jLabel29.setText("Hipertireoidismo:");
        panelProblemasDeSaude.add(jLabel29);
        jLabel29.setBounds(343, 140, 80, 14);

        jLabel30.setText("Diabétes:");
        panelProblemasDeSaude.add(jLabel30);
        jLabel30.setBounds(343, 11, 46, 14);

        jLabel31.setText("Depressão:");
        panelProblemasDeSaude.add(jLabel31);
        jLabel31.setBounds(343, 186, 55, 14);

        jLabel32.setText("Anemias:");
        panelProblemasDeSaude.add(jLabel32);
        jLabel32.setBounds(343, 36, 44, 14);

        Depressao.add(jRadioButton26);
        jRadioButton26.setSelected(true);
        jRadioButton26.setText("Não");
        panelProblemasDeSaude.add(jRadioButton26);
        jRadioButton26.setBounds(450, 182, 45, 23);

        Anemias.add(jRadioButton27);
        jRadioButton27.setSelected(true);
        jRadioButton27.setText("Não");
        panelProblemasDeSaude.add(jRadioButton27);
        jRadioButton27.setBounds(450, 32, 45, 23);

        Anemias.add(jRadioButton28);
        jRadioButton28.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton28);
        jRadioButton28.setBounds(497, 32, 41, 23);

        Depressao.add(jRadioButton29);
        jRadioButton29.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton29);
        jRadioButton29.setBounds(497, 182, 41, 23);

        Herpes.add(jRadioButton30);
        jRadioButton30.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton30);
        jRadioButton30.setBounds(497, 205, 41, 23);

        Diabetes.add(jRadioButton31);
        jRadioButton31.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton31);
        jRadioButton31.setBounds(497, 7, 41, 23);

        jLabel33.setText("Herpes:");
        panelProblemasDeSaude.add(jLabel33);
        jLabel33.setBounds(343, 209, 38, 14);

        Diabetes.add(jRadioButton32);
        jRadioButton32.setSelected(true);
        jRadioButton32.setText("Não");
        panelProblemasDeSaude.add(jRadioButton32);
        jRadioButton32.setBounds(450, 7, 45, 23);

        Herpes.add(jRadioButton33);
        jRadioButton33.setSelected(true);
        jRadioButton33.setText("Não");
        panelProblemasDeSaude.add(jRadioButton33);
        jRadioButton33.setBounds(450, 205, 45, 23);

        jLabel34.setText("Problemas Audição:");
        panelProblemasDeSaude.add(jLabel34);
        jLabel34.setBounds(343, 232, 94, 14);

        Audicao.add(jRadioButton34);
        jRadioButton34.setSelected(true);
        jRadioButton34.setText("Não");
        panelProblemasDeSaude.add(jRadioButton34);
        jRadioButton34.setBounds(450, 228, 45, 23);

        Cancer.add(jRadioButton35);
        jRadioButton35.setSelected(true);
        jRadioButton35.setText("Não");
        panelProblemasDeSaude.add(jRadioButton35);
        jRadioButton35.setBounds(450, 159, 45, 23);

        Audicao.add(jRadioButton36);
        jRadioButton36.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton36);
        jRadioButton36.setBounds(497, 228, 41, 23);

        Cancer.add(jRadioButton37);
        jRadioButton37.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton37);
        jRadioButton37.setBounds(497, 159, 41, 23);

        jLabel35.setText("Epilepsia:");
        panelProblemasDeSaude.add(jLabel35);
        jLabel35.setBounds(343, 62, 45, 14);

        Epilepsia.add(jRadioButton38);
        jRadioButton38.setSelected(true);
        jRadioButton38.setText("Não");
        panelProblemasDeSaude.add(jRadioButton38);
        jRadioButton38.setBounds(450, 58, 45, 23);

        Epilepsia.add(jRadioButton39);
        jRadioButton39.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton39);
        jRadioButton39.setBounds(497, 58, 41, 23);

        Colesterol.add(jRadioButton40);
        jRadioButton40.setText("Sim");
        panelProblemasDeSaude.add(jRadioButton40);
        jRadioButton40.setBounds(497, 84, 41, 23);

        jLabel36.setText("Alergias:");
        panelProblemasDeSaude.add(jLabel36);
        jLabel36.setBounds(570, 10, 42, 20);

        Alergias.add(rbAlergiasNao);
        rbAlergiasNao.setSelected(true);
        rbAlergiasNao.setText("Não");
        rbAlergiasNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlergiasNaoMouseClicked(evt);
            }
        });
        panelProblemasDeSaude.add(rbAlergiasNao);
        rbAlergiasNao.setBounds(620, 10, 45, 23);

        Alergias.add(rbAlergiasSim);
        rbAlergiasSim.setText("Sim");
        rbAlergiasSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlergiasSimMouseClicked(evt);
            }
        });
        panelProblemasDeSaude.add(rbAlergiasSim);
        rbAlergiasSim.setBounds(680, 10, 41, 23);

        txtAlergias.setColumns(20);
        txtAlergias.setLineWrap(true);
        txtAlergias.setRows(5);
        txtAlergias.setToolTipText("Quais?");
        txtAlergias.setEnabled(false);
        jScrollPane2.setViewportView(txtAlergias);

        panelProblemasDeSaude.add(jScrollPane2);
        jScrollPane2.setBounds(570, 40, 230, 90);

        jLabel49.setText("Observações:");
        panelProblemasDeSaude.add(jLabel49);
        jLabel49.setBounds(570, 150, 70, 14);

        txtObsSaude.setColumns(20);
        txtObsSaude.setRows(5);
        jScrollPane3.setViewportView(txtObsSaude);

        panelProblemasDeSaude.add(jScrollPane3);
        jScrollPane3.setBounds(570, 170, 230, 80);

        PaneAnamnese.addTab("Problemas de Saúde", panelProblemasDeSaude);

        jLabel37.setText("Fez alguma cirurgia?");

        Cirurgia.add(rbCirurgiaNao);
        rbCirurgiaNao.setSelected(true);
        rbCirurgiaNao.setText("Não");
        rbCirurgiaNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCirurgiaNaoMouseClicked(evt);
            }
        });
        rbCirurgiaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCirurgiaNaoActionPerformed(evt);
            }
        });

        Cirurgia.add(rbCirurgiaSim);
        rbCirurgiaSim.setText("Sim");
        rbCirurgiaSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCirurgiaSimMouseClicked(evt);
            }
        });

        jLabel38.setText("Qual?");

        txtCirurgia.setEnabled(false);

        jLabel39.setText("Fez plástica / botóx / preenchimento?");

        Plastica.add(rbPlasticaNao);
        rbPlasticaNao.setSelected(true);
        rbPlasticaNao.setText("Não");
        rbPlasticaNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPlasticaNaoMouseClicked(evt);
            }
        });

        Plastica.add(rbPlasticaSim);
        rbPlasticaSim.setText("Sim");
        rbPlasticaSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPlasticaSimMouseClicked(evt);
            }
        });

        jLabel40.setText("Onde?");

        txtPlastica.setEnabled(false);

        jLabel58.setText("Observações:");

        txtObsCirurgia.setColumns(20);
        txtObsCirurgia.setRows(5);
        jScrollPane4.setViewportView(txtObsCirurgia);

        javax.swing.GroupLayout panelProcedimentosCirurgicosLayout = new javax.swing.GroupLayout(panelProcedimentosCirurgicos);
        panelProcedimentosCirurgicos.setLayout(panelProcedimentosCirurgicosLayout);
        panelProcedimentosCirurgicosLayout.setHorizontalGroup(
            panelProcedimentosCirurgicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcedimentosCirurgicosLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(panelProcedimentosCirurgicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProcedimentosCirurgicosLayout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(panelProcedimentosCirurgicosLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPlasticaNao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPlasticaSim)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlastica, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProcedimentosCirurgicosLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCirurgiaNao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCirurgiaSim)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        panelProcedimentosCirurgicosLayout.setVerticalGroup(
            panelProcedimentosCirurgicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcedimentosCirurgicosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelProcedimentosCirurgicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(rbCirurgiaNao)
                    .addComponent(rbCirurgiaSim)
                    .addComponent(jLabel38)
                    .addComponent(txtCirurgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProcedimentosCirurgicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(rbPlasticaNao)
                    .addComponent(rbPlasticaSim)
                    .addComponent(jLabel40)
                    .addComponent(txtPlastica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProcedimentosCirurgicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        PaneAnamnese.addTab("Procedimentos Cirúrgicos / Invasivos", panelProcedimentosCirurgicos);

        jLabel41.setText("Grávida ou amamentando?");

        jLabel42.setText("Lentes de contato?");

        Gravida.add(jRadioButton47);
        jRadioButton47.setSelected(true);
        jRadioButton47.setText("Não");

        Gravida.add(jRadioButton48);
        jRadioButton48.setText("Sim");

        Lentes.add(jRadioButton49);
        jRadioButton49.setSelected(true);
        jRadioButton49.setText("Não");

        Lentes.add(jRadioButton50);
        jRadioButton50.setText("Sim");

        jLabel43.setText("Obturações dentárias de metal?");

        Obturacoes.add(jRadioButton51);
        jRadioButton51.setSelected(true);
        jRadioButton51.setText("Não");

        Obturacoes.add(jRadioButton52);
        jRadioButton52.setText("Sim");

        jLabel44.setText("Aparelho ortodôntico?");

        Aparelho.add(jRadioButton53);
        jRadioButton53.setSelected(true);
        jRadioButton53.setText("Não");

        Aparelho.add(jRadioButton54);
        jRadioButton54.setText("Sim");

        jLabel45.setText("Placas, pinos ou próteses?");

        Placas.add(jRadioButton55);
        jRadioButton55.setSelected(true);
        jRadioButton55.setText("Não");

        Placas.add(jRadioButton56);
        jRadioButton56.setText("Sim");

        jLabel46.setText("Marca-passo?");

        MarcaPasso.add(jRadioButton57);
        jRadioButton57.setSelected(true);
        jRadioButton57.setText("Não");

        MarcaPasso.add(jRadioButton58);
        jRadioButton58.setText("Sim");

        jLabel47.setText("DIU?");

        DIU.add(jRadioButton59);
        jRadioButton59.setSelected(true);
        jRadioButton59.setText("Não");

        DIU.add(jRadioButton60);
        jRadioButton60.setText("Sim");

        javax.swing.GroupLayout panelOutrosLayout = new javax.swing.GroupLayout(panelOutros);
        panelOutros.setLayout(panelOutrosLayout);
        panelOutrosLayout.setHorizontalGroup(
            panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOutrosLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelOutrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOutrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton50))
                    .addGroup(panelOutrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton52))
                    .addGroup(panelOutrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton54))
                    .addGroup(panelOutrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton56))
                    .addGroup(panelOutrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton58))
                    .addGroup(panelOutrosLayout.createSequentialGroup()
                        .addComponent(jRadioButton59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton60)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        panelOutrosLayout.setVerticalGroup(
            panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOutrosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jRadioButton47)
                    .addComponent(jRadioButton48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton49)
                    .addComponent(jRadioButton50)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton51)
                    .addComponent(jRadioButton52)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton53)
                    .addComponent(jRadioButton54)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton55)
                    .addComponent(jRadioButton56)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton57)
                    .addComponent(jRadioButton58)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton59)
                    .addComponent(jRadioButton60)
                    .addComponent(jLabel47))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        PaneAnamnese.addTab("Outros", panelOutros);

        btnCapturarImagem2.setText("Capturar");

        jLabel50.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel51.setText("Imagem 2");

        btnCapturarImagem3.setText("Capturar");

        jLabel52.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel53.setText("Imagem 3");

        btnCapturarImagem4.setText("Capturar");

        jLabel54.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel55.setText("Imagem 4");

        btnCapturarImagem1.setText("Capturar");

        jLabel56.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel57.setText("Imagem 1");

        btnCarregarImagem1.setText("Arquivo");

        btnCarregarImagem2.setText("Arquivo");

        btnCarregarImagem3.setText("Arquivo");

        btnCarregarImagem4.setText("Arquivo");

        javax.swing.GroupLayout panelFotosLayout = new javax.swing.GroupLayout(panelFotos);
        panelFotos.setLayout(panelFotosLayout);
        panelFotosLayout.setHorizontalGroup(
            panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFotosLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel57))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addComponent(btnCapturarImagem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarregarImagem1)))
                .addGap(18, 18, 18)
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel51))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addComponent(btnCapturarImagem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarregarImagem2)))
                .addGap(18, 18, 18)
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel53))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addComponent(btnCapturarImagem3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarregarImagem3)))
                .addGap(18, 18, 18)
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel55))
                    .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFotosLayout.createSequentialGroup()
                            .addComponent(btnCapturarImagem4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarregarImagem4))
                        .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        panelFotosLayout.setVerticalGroup(
            panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFotosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFotosLayout.createSequentialGroup()
                        .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCapturarImagem1)
                            .addComponent(btnCarregarImagem1)
                            .addComponent(btnCapturarImagem2)
                            .addComponent(btnCarregarImagem2)
                            .addComponent(btnCapturarImagem3)
                            .addComponent(btnCarregarImagem3)
                            .addComponent(btnCapturarImagem4)
                            .addComponent(btnCarregarImagem4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFotosLayout.createSequentialGroup()
                                .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFotosLayout.createSequentialGroup()
                                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFotosLayout.createSequentialGroup()
                                .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel55)))))
                .addContainerGap())
        );

        PaneAnamnese.addTab("Fotos", panelFotos);

        getContentPane().add(PaneAnamnese);
        PaneAnamnese.setBounds(10, 132, 830, 290);

        jPanel2.setBackground(new java.awt.Color(0, 50, 250));

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnImprimeFicha.setText("Imprimir Ficha");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addGap(18, 18, 18)
                .addComponent(btnImprimeFicha)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnGravar)
                    .addComponent(btnImprimeFicha)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 470, 850, 45);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Idade:");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(324, 72, 39, 17);

        txtIdade.setEditable(false);
        txtIdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtIdade);
        txtIdade.setBounds(367, 69, 154, 23);

        txtNome.setBackground(new java.awt.Color(153, 255, 255));
        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNome.setEnabled(false);
        getContentPane().add(txtNome);
        txtNome.setBounds(60, 70, 250, 22);

        setSize(new java.awt.Dimension(866, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void rbCirurgiaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCirurgiaNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCirurgiaNaoActionPerformed

    private void rbAlergiasSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlergiasSimMouseClicked
        txtAlergias.setEnabled(true);
        txtAlergias.grabFocus();
    }//GEN-LAST:event_rbAlergiasSimMouseClicked

    private void rbAlergiasNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlergiasNaoMouseClicked
        txtAlergias.setText("");
        txtAlergias.setEnabled(false);
    }//GEN-LAST:event_rbAlergiasNaoMouseClicked

    private void rbCirurgiaSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCirurgiaSimMouseClicked
        txtCirurgia.setEnabled(true);
        txtCirurgia.grabFocus();
    }//GEN-LAST:event_rbCirurgiaSimMouseClicked

    private void rbCirurgiaNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCirurgiaNaoMouseClicked
        txtCirurgia.setText("");
        txtCirurgia.setEnabled(false);
    }//GEN-LAST:event_rbCirurgiaNaoMouseClicked

    private void rbPlasticaNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPlasticaNaoMouseClicked
        txtPlastica.setText("");
        txtPlastica.setEnabled(false);
    }//GEN-LAST:event_rbPlasticaNaoMouseClicked

    private void rbPlasticaSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPlasticaSimMouseClicked
        txtPlastica.setEnabled(true);
        txtPlastica.grabFocus();
    }//GEN-LAST:event_rbPlasticaSimMouseClicked

    // **** Botão Gravar **************************************************************************
    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Anamnese objA = new Anamnese();
        Pacientes objP = new Pacientes();
        AnamneseDAO dao = new AnamneseDAO();
        
        
        
    }//GEN-LAST:event_btnGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnamnese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAnamnese().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Alergias;
    private javax.swing.ButtonGroup Anemias;
    private javax.swing.ButtonGroup Aparelho;
    private javax.swing.ButtonGroup Audicao;
    private javax.swing.ButtonGroup Cancer;
    private javax.swing.ButtonGroup Cardiacos;
    private javax.swing.ButtonGroup Circulatorios;
    private javax.swing.ButtonGroup Cirurgia;
    private javax.swing.ButtonGroup Colesterol;
    private javax.swing.ButtonGroup DIU;
    private javax.swing.ButtonGroup Depressao;
    private javax.swing.ButtonGroup Diabetes;
    private javax.swing.ButtonGroup Digestivos;
    private javax.swing.ButtonGroup Endocrinos;
    private javax.swing.ButtonGroup Epilepsia;
    private javax.swing.ButtonGroup Gastro;
    private javax.swing.ButtonGroup Ginecologicos;
    private javax.swing.ButtonGroup Gravida;
    private javax.swing.ButtonGroup Hepaticos;
    private javax.swing.ButtonGroup Herpes;
    private javax.swing.ButtonGroup Hiper;
    private javax.swing.ButtonGroup Hipo;
    private javax.swing.ButtonGroup Lentes;
    private javax.swing.ButtonGroup MarcaPasso;
    private javax.swing.ButtonGroup Obturacoes;
    private javax.swing.JTabbedPane PaneAnamnese;
    private javax.swing.ButtonGroup Placas;
    private javax.swing.ButtonGroup Plastica;
    private javax.swing.ButtonGroup Pressao;
    private javax.swing.ButtonGroup Renais;
    private javax.swing.ButtonGroup Respiratorios;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCapturarImagem1;
    private javax.swing.JButton btnCapturarImagem2;
    private javax.swing.JButton btnCapturarImagem3;
    private javax.swing.JButton btnCapturarImagem4;
    private javax.swing.JButton btnCarregarImagem1;
    private javax.swing.JButton btnCarregarImagem2;
    private javax.swing.JButton btnCarregarImagem3;
    private javax.swing.JButton btnCarregarImagem4;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnImprimeFicha;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton49;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton50;
    private javax.swing.JRadioButton jRadioButton51;
    private javax.swing.JRadioButton jRadioButton52;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel panelFotos;
    private javax.swing.JPanel panelHabitosDeVida;
    private javax.swing.JPanel panelOutros;
    private javax.swing.JPanel panelProblemasDeSaude;
    private javax.swing.JPanel panelProcedimentosCirurgicos;
    private javax.swing.JRadioButton rbAlergiasNao;
    private javax.swing.JRadioButton rbAlergiasSim;
    private javax.swing.JRadioButton rbCirurgiaNao;
    private javax.swing.JRadioButton rbCirurgiaSim;
    private javax.swing.JRadioButton rbPlasticaNao;
    private javax.swing.JRadioButton rbPlasticaSim;
    private javax.swing.JTextArea txtAlergias;
    private javax.swing.JTextField txtCirurgia;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JLabel txtNome;
    private javax.swing.JTextField txtNumeroAnamnese;
    private javax.swing.JTextArea txtObsCirurgia;
    private javax.swing.JTextArea txtObsSaude;
    private javax.swing.JTextArea txtObsVida;
    private javax.swing.JTextField txtPlastica;
    private javax.swing.JTextField txtQueixa;
    // End of variables declaration//GEN-END:variables
}
